[store]
[store.primary]
connection = "postgresql://graph:graph@postgres:5432/graph_node"
pool_size = 10

[deployment]
[[deployment.rule]]
match = { name = ".*" }
indexers = [ "block_ingestor_node" ]

[chains]
ingestor = "block_ingestor_node"

[chains.sepolia]
shard = "primary"
provider = [
  { label = "sepolia", url = "https://eth-sepolia.g.alchemy.com/v2/", features = ["archive", "traces"] }
]

[chains.scroll_sepolia]
shard = "primary" 
provider = [
  { label = "scroll-sepolia", url = "https://scroll-sepolia.g.alchemy.com/v2/", features = ["archive", "traces"] }
]
